-- require("noice").setup({
--     lsp = {
--         override = {
--             ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--             ["vim.lsp.util.stylize_markdown"] = true,
--             ["cmp.entry.get_documentation"] = true,
--         },
--         progress = {
--             enabled = true,
--             format = "lsp_progress",
--             format_done = "lsp_progress_done",
--             throttle = 1000 / 30, -- frequency to update lsp progress message
--             view = "mini",
--         },
--         hover = {
--             enabled = true,
--             silent = false, -- set to true to not show a message if hover is not available
--             view = nil,     -- when nil, use defaults from documentation
--             opts = {},      -- merged with defaults from documentation
--         },
--         message = {
--             -- Messages shown by lsp servers
--             enabled = true,
--             view = "notify",
--             opts = {},
--         },
--         -- defaults for hover and signature help
--         documentation = {
--             view = "hover",
--             opts = {
--                 lang = "markdown",
--                 replace = true,
--                 render = "plain",
--                 format = { "{message}" },
--                 win_options = { concealcursor = "n", conceallevel = 3 },
--             },
--         },
--     },
--     presets = {
--         bottom_search = true,         -- use a classic bottom cmdline for search
--         command_palette = true,       -- position the cmdline and popupmenu together
--         long_message_to_split = true, -- long messages will be sent to a split
--         inc_rename = false,           -- enables an input dialog for inc-rename.nvim
--         lsp_doc_border = false,       -- add a border to hover docs and signature help
--     },
--     throttle = 1000 / 30,          -- how frequently does Noice need to check for ui updates? This has no effect when in blocking mode.
--     views = {}, ---@see section on views
--     background_coluor = "#000000"
-- })
